require('catppuccin').setup {
  integrations = {
    alpha = false,
    dap = false,
    dap_ui = false,
    dashboard = false,
    flash = false,
    neogit = false,
    mini = { enabled = false },
    nvimtree = false,
    ufo = false,

    treesitter = true,
    native_lsp = { enabled = true },
    cmp = true,
    dropbar = { enabled = true, color_mode = true },
    gitsigns = true,
    headlines = true,
    illuminate = true,
    indent_blankline = { enabled = true, scope_color = 'surface2' },
    markdown = true,
    rainbow_delimiters = true,
    semantic_tokens = true,
    telescope = { enabled = true, style = 'nvchad' },
  },
  highlight_overrides = {
    all = function(cp)
      return {
        WinSeparator = { fg = cp.surface0 },
        NormalFloat = { bg = cp.mantle },
        FloatBorder = { bg = cp.mantle, fg = cp.mantle },
        FloatTitle = { bg = cp.mantle, fg = cp.mantle },
        LspInfoBorder = { link = 'FloatBorder' },

        StatusLineHeader = { bg = cp.crust, fg = cp.mauve },
        StatusLineHeaderModified = { bg = cp.crust, fg = cp.peach },

        GlanceBorderTop = { fg = cp.mauve },
        GlanceIndent = { link = 'None' },
        GlanceListBorderBottom = { link = 'GlanceBorderTop' },
        GlanceListCount = { bg = cp.pink, fg = cp.base },
        GlanceListCursorLine = { bg = cp.surface0 },
        GlanceListMatch = { fg = cp.blue },
        GlanceListNormal = { bg = cp.mantle, fg = cp.text },
        GlancePreviewBorderBottom = { link = 'GlanceBorderTop' },
        GlancePreviewNormal = { bg = cp.crust, fg = cp.text },
        GlanceWinBarFilename = { bg = cp.crust, fg = cp.text },
        GlanceWinBarFilepath = { bg = cp.crust, fg = cp.subtext0 },
        GlanceWinBarTitle = { bg = cp.mantle, fg = cp.text, bold = true },

        TelescopePreviewBorder = { bg = cp.crust, fg = cp.crust },
        TelescopePreviewNormal = { bg = cp.crust },
        TelescopePreviewTitle = { fg = cp.crust, bg = cp.crust },
        TelescopePromptBorder = {
          bg = cp.surface0,
          fg = cp.surface0,
        },
        TelescopePromptCounter = { fg = cp.mauve, style = { 'bold' } },
        TelescopePromptNormal = { bg = cp.surface0 },
        TelescopePromptPrefix = { bg = cp.surface0 },
        TelescopePromptTitle = {
          fg = cp.surface0,
          bg = cp.surface0,
        },
        TelescopeResultsBorder = { bg = cp.mantle, fg = cp.mantle },
        TelescopeResultsNormal = { bg = cp.mantle },
        TelescopeResultsTitle = { fg = cp.mantle, bg = cp.mantle },
      }
    end,
  },
}
