require('ibl').setup {
  indent = { char = '▏' },
  scope = {
    show_start = false,
    show_end = false,
    injected_languages = true,
    include = {
      node_type = {
        ['*'] = {
          'argument_list',
          'arguments',
          'assignment_statement',
          'Block',
          'chunk',
          'class',
          'ContainerDecl',
          'dictionary',
          'do_block',
          'do_statement',
          'element',
          'except',
          'FnCallArguments',
          'for',
          'for_statement',
          'function',
          'function_declaration',
          'function_definition',
          'if_statement',
          'IfExpr',
          'IfStatement',
          'import',
          'InitList',
          'list_literal',
          'method',
          'object',
          'ParamDeclList',
          'repeat_statement',
          'selector',
          'SwitchExpr',
          'table',
          'table_constructor',
          'try',
          'tuple',
          'type',
          'var',
          'while',
          'while_statement',
          'with',
        },
      },
    },
  },
}
