PREF = {
  editor = {
    tabsize = 2,
  },
  ui = {
    border = 'shadow',
    border_interactive = 'rounded',
    border_hover = 'none',
    show_peek_border = false,
  },
  git = {
    show_signcolumn = true,
    show_blame = false,
  },
  lsp_servers = {
    'bashls',
    'clangd',
    'cssls',
    'html',
    'jsonls',
    'lua_ls',
    'marksman',
    'nil_ls',
    'pyright',
    'rust_analyzer',
    -- 'tsserver', -- replaced with typescript.nvim
    'yamlls',
  },
  treesitter = {
    'c',
    'cpp',
    'css',
    'gitcommit',
    'gitignore',
    'html',
    'ini',
    'javascript',
    'jsdoc',
    'json',
    'lua',
    'make',
    'markdown',
    'markdown_inline',
    'nix',
    'python',
    'rust',
    'typescript',
    'tsx',
    'vim',
    'vimdoc',
    'yaml',
  },
  formatters = {
    c = { 'clang-format' },
    cpp = { 'clang-format' },
    html = { { 'prettierd', 'prettier' } },
    javascript = { { 'prettierd', 'prettier' }, { 'eslint_d', 'eslint' } },
    javascriptreact = {
      { 'prettierd', 'prettier' },
      { 'eslint_d', 'eslint' },
    },
    json = { { 'prettierd', 'prettier' } },
    lua = { 'stylua' },
    markdown = { { 'prettierd', 'prettier' } },
    nix = { 'nixfmt' },
    python = { 'black' },
    rust = { 'rustfmt' },
    typescript = { { 'prettierd', 'prettier' }, { 'eslint_d', 'eslint' } },
    typescriptreact = {
      { 'prettierd', 'prettier' },
      { 'eslint_d', 'eslint' },
    },
    sh = { 'shfmt' },
    toml = { { 'prettierd', 'prettier' } },
    vue = { { 'prettierd', 'prettier' }, { 'eslint_d', 'eslint' } },
    yaml = { { 'prettierd', 'prettier' } },
  },
  icons = {
    diagnostics = {
      Error = '󰅚 ',
      Hint = '󰌶 ',
      Info = '󰋽 ',
      Ok = '󰄬 ',
      Warn = '󰀪 ',
    },
    kinds = {
      Array = '󰅪 ',
      Boolean = ' ',
      BreakStatement = '󰙧 ',
      Calculator = '󰃬 ',
      Call = '󰃷 ',
      CaseStatement = '󱃙 ',
      Class = ' ',
      Color = '󰏘 ',
      Constant = '󰏿 ',
      Constructor = '󰒓 ',
      ContinueStatement = '→ ',
      Declaration = '󰙠 ',
      Delete = '󰩺 ',
      DoStatement = '󰑖 ',
      Enum = ' ',
      EnumMember = ' ',
      Event = '󱐋 ',
      Field = ' ',
      File = '󰈔 ',
      Folder = '󰉋 ',
      ForStatement = '󰑖 ',
      Format = '󰗈 ',
      Function = '󰊕 ',
      GitBranch = ' ',
      H1Marker = '󰉫 ',
      H2Marker = '󰉬 ',
      H3Marker = '󰉭 ',
      H4Marker = '󰉮 ',
      H5Marker = '󰉯 ',
      H6Marker = '󰉰 ',
      Identifier = '󰀫 ',
      IfStatement = '󰇉 ',
      Interface = ' ',
      Keyword = '󰌋 ',
      List = '󰅪 ',
      Log = '󰦪 ',
      Lsp = ' ',
      Macro = '󰁌 ',
      MarkdownH1 = '󰉫 ',
      MarkdownH2 = '󰉬 ',
      MarkdownH3 = '󰉭 ',
      MarkdownH4 = '󰉮 ',
      MarkdownH5 = '󰉯 ',
      MarkdownH6 = '󰉰 ',
      Method = '󰆧 ',
      Module = '󰏗 ',
      Namespace = '󰅩 ',
      Null = '󰢤 ',
      Number = '󰎠 ',
      Object = '󰅩 ',
      Operator = '󰆕 ',
      Package = '󰆦 ',
      Pair = '󰅪 ',
      Property = '󰓹 ',
      Reference = '󰦾 ',
      Regex = ' ',
      Repeat = '󰑖 ',
      Scope = '󰅩 ',
      Snippet = '󰩫 ',
      Specifier = '󰦪 ',
      Statement = '󰅩 ',
      String = '󰉾 ',
      Struct = ' ',
      SwitchStatement = '󰺟 ',
      Terminal = ' ',
      Text = ' ',
      Type = '󰠲 ',
      TypeParameter = '󰆩 ',
      Unit = '󰑭 ',
      Value = '󰎠 ',
      Variable = '󰀫 ',
      WhileStatement = '󰑖 ',
    },
    ui = {
      AngleDown = '󰅀 ',
      AngleLeft = '󰅁 ',
      AngleRight = '󰅂 ',
      AngleUp = '󰅃 ',
      ArrowDown = '󰁅 ',
      ArrowLeft = '󰁍 ',
      ArrowRight = '󰁔 ',
      ArrowUp = '󰁝 ',
      Code = '󰅴 ',
      Command = '󰘳 ',
      Circle = '󰧞 ',
      Ellipsis = '… ',
      Flag = '󰈼 ',
      Ghost = '󰊠 ',
      Import = '󰋺 ',
      Keyboard = '󰌌 ',
      Sleep = '󰒲 ',
      TimerPlay = '󱫠 ',
      TriangleDown = '▼ ',
      TriangleLeft = '◀ ',
      TriangleRight = '▶ ',
      TriangleUp = '▲ ',
    },
  },
}
