PREF = {
  editor = {
    tabsize = 2,
  },
  ui = {
    border = vim.g.gui and 'solid' or 'single',
    border_interactive = 'rounded',
    border_hover = 'solid',
    show_peek_border = false,
    show_fold_signcolumn = false,
    show_git_signcolumn = true,
    show_git_blame = false,
  },
  lsp_servers = {
    'bashls',
    'clangd',
    'cssls',
    'html',
    'jedi_language_server',
    'jsonls',
    'lua_ls',
    'nixd',
    'rust_analyzer',
    -- 'tsserver', -- replaced with typescript.nvim
    'yamlls',
  },
  treesitter = {
    'c',
    'cpp',
    'css',
    'diff',
    'gitcommit',
    'gitignore',
    'html',
    'ini',
    'javascript',
    'jsdoc',
    'json',
    'lua',
    'make',
    'markdown',
    'markdown_inline',
    'nix',
    'python',
    'rust',
    'scss',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'xml',
    'yaml',
  },
  formatters = {
    c = { 'clang-format' },
    cpp = { 'clang-format' },
    html = { 'prettier' },
    javascript = { 'prettier', 'eslint' },
    javascriptreact = {
      'prettier',
      'eslint',
    },
    json = { 'prettier' },
    lua = { 'stylua' },
    markdown = { 'prettier' },
    nix = { 'nixfmt' },
    python = { 'black' },
    typescript = { 'prettier', 'eslint' },
    typescriptreact = { 'prettier', 'eslint' },
    sh = { 'shfmt' },
    toml = { 'prettier' },
    vue = { 'prettier', 'eslint' },
    yaml = { 'prettier' },
  },
  icons = vim.g.gui and {
    diagnostics = {
      Error = '󰅚 ',
      Hint = '󰌶 ',
      Info = '󰋽 ',
      Ok = '󰄬 ',
      Warn = '󰀪 ',
    },
    kinds = {
      Array = '󰅪 ',
      Boolean = ' ',
      BreakStatement = '󰙧 ',
      Calculator = '󰃬 ',
      Call = '󰃷 ',
      CaseStatement = '󱃙 ',
      Class = ' ',
      Color = '󰏘 ',
      Constant = '󰏿 ',
      Constructor = '󰒓 ',
      ContinueStatement = '→ ',
      Declaration = '󰙠 ',
      Delete = '󰩺 ',
      DoStatement = '󰑖 ',
      Enum = ' ',
      EnumMember = ' ',
      Event = '󱐋 ',
      Field = ' ',
      File = '󰈔 ',
      Folder = '󰉋 ',
      ForStatement = '󰑖 ',
      Format = '󰗈 ',
      Function = '󰊕 ',
      GitBranch = ' ',
      H1Marker = '󰉫 ',
      H2Marker = '󰉬 ',
      H3Marker = '󰉭 ',
      H4Marker = '󰉮 ',
      H5Marker = '󰉯 ',
      H6Marker = '󰉰 ',
      Identifier = '󰀫 ',
      IfStatement = '󰇉 ',
      Interface = ' ',
      Keyword = '󰌋 ',
      List = '󰅪 ',
      Log = '󰦪 ',
      Lsp = ' ',
      Macro = '󰁌 ',
      MarkdownH1 = '󰉫 ',
      MarkdownH2 = '󰉬 ',
      MarkdownH3 = '󰉭 ',
      MarkdownH4 = '󰉮 ',
      MarkdownH5 = '󰉯 ',
      MarkdownH6 = '󰉰 ',
      Method = '󰆧 ',
      Module = '󰏗 ',
      Namespace = '󰅩 ',
      Null = '󰢤 ',
      Number = '󰎠 ',
      Object = '󰅩 ',
      Operator = '󰆕 ',
      Package = '󰆦 ',
      Pair = '󰅪 ',
      Property = '󰓹 ',
      Reference = '󰦾 ',
      Regex = ' ',
      Repeat = '󰑖 ',
      Scope = '󰅩 ',
      Snippet = '󰩫 ',
      Specifier = '󰦪 ',
      Statement = '󰅩 ',
      String = '󰉾 ',
      Struct = ' ',
      SwitchStatement = '󰺟 ',
      Terminal = ' ',
      Text = ' ',
      Type = '󰠲 ',
      TypeParameter = '󰆩 ',
      Unit = '󰑭 ',
      Value = '󰎠 ',
      Variable = '󰀫 ',
      WhileStatement = '󰑖 ',
    },
    ui = {
      AngleDown = '󰅀 ',
      AngleLeft = '󰅁 ',
      AngleRight = '󰅂 ',
      AngleUp = '󰅃 ',
      ArrowDown = '󰁅 ',
      ArrowLeft = '󰁍 ',
      ArrowRight = '󰁔 ',
      ArrowUp = '󰁝 ',
      Circle = '󰧞 ',
      CircleFilled = '󰝥 ',
      CircleEmpty = '󰝦 ',
      Cmd = '󰘳 ',
      Ellipsis = '… ',
      Flag = '󰈼 ',
      GitSignAdd = '▍ ',
      GitSignChange = '▍ ',
      GitSignChangedelete = '▍ ',
      GitSignDelete = '▁ ',
      GitSignTopdelete = '▔ ',
      GitSignUntracked = '▍ ',
      Keyboard = '󰌌 ',
      Neovim = ' ',
      Sleep = '󰒲 ',
      TriangleDown = '▼ ',
      TriangleLeft = '◀ ',
      TriangleRight = '▶ ',
      TriangleUp = '▲ ',
      Vim = ' ',
    },
  } or {
    diagnostics = {
      Error = 'E ',
      Hint = 'H ',
      Info = 'I ',
      Ok = 'O ',
      Warn = 'W ',
    },
    kinds = {
      Array = 'A ',
      Boolean = 'B ',
      BreakStatement = 'B ',
      Calculator = 'C ',
      Call = 'C ',
      CaseStatement = 'C ',
      Class = 'C ',
      Color = 'C ',
      Constant = 'C ',
      Constructor = 'C ',
      ContinueStatement = '→ ',
      Declaration = 'D ',
      Delete = 'D ',
      DoStatement = 'D ',
      Enum = 'E ',
      EnumMember = 'E ',
      Event = 'E ',
      Field = 'F ',
      File = 'F ',
      Folder = 'D ',
      ForStatement = 'F ',
      Format = 'F ',
      Function = 'F ',
      GitBranch = 'F ',
      H1Marker = '1 ',
      H2Marker = '2 ',
      H3Marker = '3 ',
      H4Marker = '4 ',
      H5Marker = '5 ',
      H6Marker = '6 ',
      Identifier = 'I ',
      IfStatement = '? ',
      Interface = 'I ',
      Keyword = 'K ',
      List = 'L ',
      Log = 'L ',
      Lsp = 'L ',
      Macro = '# ',
      MarkdownH1 = '1 ',
      MarkdownH2 = '2 ',
      MarkdownH3 = '3 ',
      MarkdownH4 = '4 ',
      MarkdownH5 = '5 ',
      MarkdownH6 = '6 ',
      Method = 'M ',
      Module = 'M ',
      Namespace = 'N ',
      Null = 'N ',
      Number = 'N ',
      Object = 'O ',
      Operator = 'O ',
      Package = 'P ',
      Pair = 'P ',
      Property = '+ ',
      Reference = 'R ',
      Regex = 'R ',
      Repeat = 'R ',
      Scope = 'S ',
      Snippet = 'S ',
      Specifier = 'S ',
      Statement = 'S ',
      String = 'S ',
      Struct = 'S ',
      SwitchStatement = 'S ',
      Terminal = 'T ',
      Text = 'T ',
      Type = 'T ',
      TypeParameter = 'T ',
      Unit = 'U ',
      Value = 'V ',
      Variable = 'V ',
      WhileStatement = 'W ',
    },
    ui = {
      AngleDown = 'v ',
      AngleLeft = '< ',
      AngleRight = '> ',
      AngleUp = '^ ',
      ArrowDown = '↓ ',
      ArrowLeft = '← ',
      ArrowRight = '→ ',
      ArrowUp = '↑ ',
      Circle = '• ',
      CircleFilled = '◆ ',
      CircleEmpty = '○ ',
      Cmd = '> ',
      Ellipsis = '. ',
      Flag = 'F ',
      GitSignAdd = '+ ',
      GitSignChange = '~ ',
      GitSignChangedelete = '= ',
      GitSignDelete = '- ',
      GitSignTopdelete = '- ',
      GitSignUntracked = '+ ',
      Keyboard = 'K ',
      Neovim = 'N ',
      Sleep = 'Z ',
      TriangleDown = '▼ ',
      TriangleLeft = '◀ ',
      TriangleRight = '▶ ',
      TriangleUp = '▲ ',
      Vim = 'V ',
    },
  },
}
